version: '3.2'

services:
  redis:
    build:
      context: redis/
    volumes:
      - /redis-data/data:/data
    ports:
            - "6379:6379"
    networks:
      - redis 

    restart: always

networks:
  redis:
    driver:  bridge 

